/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ipquery_CONSTANTS_H
#define ipquery_CONSTANTS_H

#include "ipquery_types.h"

namespace ipquery {

class ipqueryConstants {
 public:
  ipqueryConstants();

};

extern const ipqueryConstants g_ipquery_constants;

} // namespace

#endif
