/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "ipquery_constants.h"

namespace ipquery {

const ipqueryConstants g_ipquery_constants;

ipqueryConstants::ipqueryConstants() {
}

} // namespace

